// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef _PRINTPOOP_UI_H
#define _PRINTPOOP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_screen_intro.h"
#include "ui_screen_setup.h"
#include "ui_screen_status.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * spin_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * slowblink_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * sway_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * shake_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * gif_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * swing_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui_startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_front_cover_png);   // assets/front_cover.png
LV_IMG_DECLARE( ui_img_cap_png);   // assets/cap.png
LV_IMG_DECLARE( ui_img_cat1_png);   // assets/cat1.png
LV_IMG_DECLARE( ui_img_ap_qr_png);   // assets/ap_qr.png
LV_IMG_DECLARE( ui_img_ipaddress_png);   // assets/ipaddress.png
LV_IMG_DECLARE( ui_img_printer_png);   // assets/printer.png
LV_IMG_DECLARE( ui_img_ams_png);   // assets/ams.png
LV_IMG_DECLARE( ui_img_stage_1_png);   // assets/stage_1.png
LV_IMG_DECLARE( ui_img_swing_png);   // assets/swing.png
LV_IMG_DECLARE( ui_img_print_status_png);   // assets/print_status.png
LV_IMG_DECLARE( ui_img_print_head_png);   // assets/print_head.png
LV_IMG_DECLARE( ui_img_empty_png);   // assets/empty.png
LV_IMG_DECLARE( ui_img_ams_box_png);   // assets/ams_box.png
LV_IMG_DECLARE( ui_img_cat2_png);   // assets/cat2.png
LV_IMG_DECLARE( ui_img_cat3_png);   // assets/cat3.png
LV_IMG_DECLARE( ui_img_stage0_png);   // assets/stage0.png
LV_IMG_DECLARE( ui_img_stage1_png);   // assets/stage1.png
LV_IMG_DECLARE( ui_img_stage13_png);   // assets/stage13.png
LV_IMG_DECLARE( ui_img_stage14_png);   // assets/stage14.png
LV_IMG_DECLARE( ui_img_stage2_png);   // assets/stage2.png
LV_IMG_DECLARE( ui_img_stage24_png);   // assets/stage24.png
LV_IMG_DECLARE( ui_img_stage255_png);   // assets/stage255.png
LV_IMG_DECLARE( ui_img_stage4_png);   // assets/stage4.png
LV_IMG_DECLARE( ui_img_stage5_png);   // assets/stage5.png
LV_IMG_DECLARE( ui_img_stage8_png);   // assets/stage8.png

// FONTS
LV_FONT_DECLARE( ui_font_orangekid32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
