// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void wait5second(lv_event_t * e);
void openSetupPortal(lv_event_t * e);
void closeSetupScreen(lv_event_t * e);
void switch_previous_page(lv_event_t * e);
void switch_next_page(lv_event_t * e);
void closeSwingAnimation(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
