// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef UI_SCREEN_INTRO_H
#define UI_SCREEN_INTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_intro
extern void ui_screen_intro_screen_init(void);
extern void ui_screen_intro_screen_destroy(void);
extern void ui_event_screen_intro( lv_event_t * e);
extern lv_obj_t *ui_screen_intro;
extern lv_obj_t *ui_intro_image_cap;
extern lv_obj_t *ui_intro_label_version;
extern lv_obj_t *ui_intro_image_icon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

