// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: printpoop

#include "ui.h"

lv_obj_t *ui_screen_status = NULL;lv_obj_t *ui_status_label_printstage = NULL;lv_obj_t *ui_status_label_wifisymbol = NULL;lv_obj_t *ui_status_image_printer = NULL;lv_obj_t *ui_status_image_ams = NULL;lv_obj_t *ui_status_button_networksetup = NULL;lv_obj_t *ui_status_label_label1 = NULL;lv_obj_t *ui_status_panel_page0 = NULL;lv_obj_t *ui_status_image_swing = NULL;lv_obj_t *ui_status_bar_mcpercent2 = NULL;lv_obj_t *ui_status_image_ppimage = NULL;lv_obj_t *ui_status_label_ppmessage = NULL;lv_obj_t *ui_status_panel_page1 = NULL;lv_obj_t *ui_status_image_printbase = NULL;lv_obj_t *ui_status_image_printhead = NULL;lv_obj_t *ui_status_label_nozzletemp = NULL;lv_obj_t *ui_status_label_bedtemp = NULL;lv_obj_t *ui_status_label_chambertemp = NULL;lv_obj_t *ui_status_bar_coolingfan = NULL;lv_obj_t *ui_status_bar_heatbreakfan = NULL;lv_obj_t *ui_status_spinner_spinner2 = NULL;lv_obj_t *ui_status_spinner_spinner1 = NULL;lv_obj_t *ui_status_bar_mcpercent = NULL;lv_obj_t *ui_status_panel_page2 = NULL;lv_obj_t *ui_status_label_mcremaintime = NULL;lv_obj_t *ui_status_label_clock = NULL;lv_obj_t *ui_status_arc_mcpercentarc = NULL;lv_obj_t *ui_status_label_layernum = NULL;lv_obj_t *ui_status_label_layertotal = NULL;lv_obj_t *ui_status_panel_page3 = NULL;lv_obj_t *ui_status_image_checker = NULL;lv_obj_t *ui_status_button_slot1 = NULL;lv_obj_t *ui_status_button_slot2 = NULL;lv_obj_t *ui_status_button_slot3 = NULL;lv_obj_t *ui_status_button_slot4 = NULL;lv_obj_t *ui_status_button_slot0 = NULL;lv_obj_t *ui_status_image_amsbox = NULL;lv_obj_t *ui_status_label_filament1 = NULL;lv_obj_t *ui_status_label_filament2 = NULL;lv_obj_t *ui_status_label_filament3 = NULL;lv_obj_t *ui_status_label_filament4 = NULL;lv_obj_t *ui_status_label_filament0 = NULL;
// event funtions
void ui_event_screen_status( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      switch_previous_page( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      switch_next_page( e );
}
}

void ui_event_status_button_networksetup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setup, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_screen_setup_screen_init);
}
}

void ui_event_status_panel_page0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      closeSwingAnimation( e );
}
}

// build funtions

void ui_screen_status_screen_init(void)
{
ui_screen_status = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_status, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_screen_status, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_screen_status, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_screen_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_screen_status, lv_color_hex(0xFF3802), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_screen_status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_screen_status, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_screen_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_screen_status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_screen_status, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_screen_status, -7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_printstage = lv_label_create(ui_screen_status);
lv_obj_set_width( ui_status_label_printstage, 224);
lv_obj_set_height( ui_status_label_printstage, 34);
lv_obj_set_x( ui_status_label_printstage, 0 );
lv_obj_set_y( ui_status_label_printstage, -93 );
lv_obj_set_align( ui_status_label_printstage, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_status_label_printstage,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_printstage,"PrintpooP");
lv_obj_clear_flag( ui_status_label_printstage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_printstage, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_printstage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_printstage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_printstage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_label_printstage, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_label_printstage, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_label_printstage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_label_printstage, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_label_printstage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_status_label_printstage, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_status_label_printstage, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_status_label_printstage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_status_label_printstage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_status_label_printstage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_wifisymbol = lv_label_create(ui_screen_status);
lv_obj_set_width( ui_status_label_wifisymbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_wifisymbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_wifisymbol, 7 );
lv_obj_set_y( ui_status_label_wifisymbol, 1 );
lv_label_set_text(ui_status_label_wifisymbol,"W");
lv_obj_set_style_text_color(ui_status_label_wifisymbol, lv_color_hex(0x02CFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_wifisymbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_label_wifisymbol, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_image_printer = lv_img_create(ui_screen_status);
lv_img_set_src(ui_status_image_printer, &ui_img_printer_png);
lv_obj_set_width( ui_status_image_printer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_printer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_printer, -36 );
lv_obj_set_y( ui_status_image_printer, 5 );
lv_obj_set_align( ui_status_image_printer, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_status_image_printer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_printer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status_image_ams = lv_img_create(ui_screen_status);
lv_img_set_src(ui_status_image_ams, &ui_img_ams_png);
lv_obj_set_width( ui_status_image_ams, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_ams, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_ams, 6 );
lv_obj_set_y( ui_status_image_ams, 5 );
lv_obj_set_align( ui_status_image_ams, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_status_image_ams, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_ams, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status_button_networksetup = lv_btn_create(ui_screen_status);
lv_obj_set_width( ui_status_button_networksetup, 70);
lv_obj_set_height( ui_status_button_networksetup, 30);
lv_obj_set_x( ui_status_button_networksetup, -5 );
lv_obj_set_y( ui_status_button_networksetup, 5 );
lv_obj_set_align( ui_status_button_networksetup, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_status_button_networksetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_status_button_networksetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_status_button_networksetup, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_networksetup, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_networksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_networksetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_networksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_status_button_networksetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_button_networksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_button_networksetup, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_button_networksetup, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_label1 = lv_label_create(ui_status_button_networksetup);
lv_obj_set_width( ui_status_label_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_status_label_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_label1,"SETUP");

ui_status_panel_page0 = lv_obj_create(ui_screen_status);
lv_obj_set_width( ui_status_panel_page0, 220);
lv_obj_set_height( ui_status_panel_page0, 220);
lv_obj_set_x( ui_status_panel_page0, 0 );
lv_obj_set_y( ui_status_panel_page0, 39 );
lv_obj_set_align( ui_status_panel_page0, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_panel_page0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_status_panel_page0, lv_color_hex(0x71DAE6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_panel_page0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_panel_page0, lv_color_hex(0x14262A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_status_panel_page0, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_panel_page0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_panel_page0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_status_panel_page0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_panel_page0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_panel_page0, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_image_swing = lv_img_create(ui_status_panel_page0);
lv_img_set_src(ui_status_image_swing, &ui_img_swing_png);
lv_obj_set_width( ui_status_image_swing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_swing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_swing, 0 );
lv_obj_set_y( ui_status_image_swing, -8 );
lv_obj_set_align( ui_status_image_swing, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_image_swing, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_swing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_status_image_swing,64,0);

ui_status_bar_mcpercent2 = lv_bar_create(ui_status_panel_page0);
lv_obj_set_width( ui_status_bar_mcpercent2, 200);
lv_obj_set_height( ui_status_bar_mcpercent2, 12);
lv_obj_set_x( ui_status_bar_mcpercent2, 0 );
lv_obj_set_y( ui_status_bar_mcpercent2, -191 );
lv_obj_set_align( ui_status_bar_mcpercent2, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_status_bar_mcpercent2, lv_color_hex(0x102829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_mcpercent2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_bar_mcpercent2, lv_color_hex(0xF6BF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_bar_mcpercent2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_status_bar_mcpercent2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_status_bar_mcpercent2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_status_bar_mcpercent2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_bar_mcpercent2, lv_color_hex(0xFEFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_mcpercent2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_bar_mcpercent2, lv_color_hex(0x303030), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_status_bar_mcpercent2, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_image_ppimage = lv_img_create(ui_status_panel_page0);
lv_img_set_src(ui_status_image_ppimage, &ui_img_stage_1_png);
lv_obj_set_width( ui_status_image_ppimage, LV_SIZE_CONTENT);  /// 128
lv_obj_set_height( ui_status_image_ppimage, LV_SIZE_CONTENT);   /// 128
lv_obj_set_x( ui_status_image_ppimage, 0 );
lv_obj_set_y( ui_status_image_ppimage, -6 );
lv_obj_set_align( ui_status_image_ppimage, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_status_image_ppimage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_ppimage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_status_image_ppimage,255);

ui_status_label_ppmessage = lv_label_create(ui_status_panel_page0);
lv_obj_set_width( ui_status_label_ppmessage, 218);
lv_obj_set_height( ui_status_label_ppmessage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_ppmessage, 1 );
lv_obj_set_y( ui_status_label_ppmessage, 99 );
lv_obj_set_align( ui_status_label_ppmessage, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_status_label_ppmessage,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_ppmessage,"Meow! I am PrintpooP (Swipe left/right for pages)");
lv_obj_set_style_text_color(ui_status_label_ppmessage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_ppmessage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_ppmessage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_label_ppmessage, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_panel_page1 = lv_obj_create(ui_screen_status);
lv_obj_set_width( ui_status_panel_page1, 220);
lv_obj_set_height( ui_status_panel_page1, 220);
lv_obj_set_x( ui_status_panel_page1, 0 );
lv_obj_set_y( ui_status_panel_page1, 39 );
lv_obj_set_align( ui_status_panel_page1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_panel_page1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status_panel_page1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_status_panel_page1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_panel_page1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_panel_page1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_panel_page1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_status_panel_page1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_panel_page1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_panel_page1, &ui_font_orangekid32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_image_printbase = lv_img_create(ui_status_panel_page1);
lv_img_set_src(ui_status_image_printbase, &ui_img_print_status_png);
lv_obj_set_width( ui_status_image_printbase, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_printbase, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_printbase, 0 );
lv_obj_set_y( ui_status_image_printbase, -20 );
lv_obj_set_align( ui_status_image_printbase, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_image_printbase, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_printbase, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status_image_printhead = lv_img_create(ui_status_panel_page1);
lv_img_set_src(ui_status_image_printhead, &ui_img_print_head_png);
lv_obj_set_width( ui_status_image_printhead, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_printhead, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_printhead, -6 );
lv_obj_set_y( ui_status_image_printhead, -58 );
lv_obj_set_align( ui_status_image_printhead, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_image_printhead, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_printhead, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status_label_nozzletemp = lv_label_create(ui_status_panel_page1);
lv_obj_set_width( ui_status_label_nozzletemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_nozzletemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_nozzletemp, 120 );
lv_obj_set_y( ui_status_label_nozzletemp, -4 );
lv_obj_set_align( ui_status_label_nozzletemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_status_label_nozzletemp,"0/0");
lv_obj_set_style_text_color(ui_status_label_nozzletemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_nozzletemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_nozzletemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_bedtemp = lv_label_create(ui_status_panel_page1);
lv_obj_set_width( ui_status_label_bedtemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_bedtemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_bedtemp, 0 );
lv_obj_set_y( ui_status_label_bedtemp, 83 );
lv_obj_set_align( ui_status_label_bedtemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_bedtemp,"0/0");
lv_obj_clear_flag( ui_status_label_bedtemp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_bedtemp, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_bedtemp, lv_color_hex(0xF2FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_bedtemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_bedtemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_chambertemp = lv_label_create(ui_status_panel_page1);
lv_obj_set_width( ui_status_label_chambertemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_chambertemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_chambertemp, 12 );
lv_obj_set_y( ui_status_label_chambertemp, -17 );
lv_obj_set_align( ui_status_label_chambertemp, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_status_label_chambertemp,"0");
lv_obj_set_style_text_color(ui_status_label_chambertemp, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_chambertemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_chambertemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_bar_coolingfan = lv_bar_create(ui_status_panel_page1);
lv_bar_set_range(ui_status_bar_coolingfan, 0,15);
lv_obj_set_width( ui_status_bar_coolingfan, 80);
lv_obj_set_height( ui_status_bar_coolingfan, 10);
lv_obj_set_x( ui_status_bar_coolingfan, -58 );
lv_obj_set_y( ui_status_bar_coolingfan, 9 );
lv_obj_set_align( ui_status_bar_coolingfan, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_status_bar_coolingfan, lv_color_hex(0x01303B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_coolingfan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_status_bar_coolingfan, lv_color_hex(0x04EEFD), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_coolingfan, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_bar_heatbreakfan = lv_bar_create(ui_status_panel_page1);
lv_bar_set_range(ui_status_bar_heatbreakfan, 0,15);
lv_obj_set_width( ui_status_bar_heatbreakfan, 80);
lv_obj_set_height( ui_status_bar_heatbreakfan, 10);
lv_obj_set_x( ui_status_bar_heatbreakfan, -58 );
lv_obj_set_y( ui_status_bar_heatbreakfan, -20 );
lv_obj_set_align( ui_status_bar_heatbreakfan, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_status_bar_heatbreakfan, lv_color_hex(0x3B0139), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_heatbreakfan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_status_bar_heatbreakfan, lv_color_hex(0xEB04FD), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_heatbreakfan, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_spinner_spinner2 = lv_spinner_create(ui_status_panel_page1,1000,90);
lv_obj_set_width( ui_status_spinner_spinner2, 24);
lv_obj_set_height( ui_status_spinner_spinner2, 24);
lv_obj_set_x( ui_status_spinner_spinner2, -93 );
lv_obj_set_y( ui_status_spinner_spinner2, -20 );
lv_obj_set_align( ui_status_spinner_spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_spinner_spinner2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_spinner_spinner2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_arc_color(ui_status_spinner_spinner2, lv_color_hex(0x390039), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_spinner_spinner2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status_spinner_spinner2, lv_color_hex(0xC703FE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_spinner_spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status_spinner_spinner2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_spinner_spinner1 = lv_spinner_create(ui_status_panel_page1,1000,90);
lv_obj_set_width( ui_status_spinner_spinner1, 24);
lv_obj_set_height( ui_status_spinner_spinner1, 24);
lv_obj_set_x( ui_status_spinner_spinner1, -93 );
lv_obj_set_y( ui_status_spinner_spinner1, 9 );
lv_obj_set_align( ui_status_spinner_spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_spinner_spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_status_spinner_spinner1, lv_color_hex(0x003039), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_spinner_spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status_spinner_spinner1, lv_color_hex(0x03B9FE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_spinner_spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status_spinner_spinner1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_bar_mcpercent = lv_bar_create(ui_status_panel_page1);
lv_obj_set_width( ui_status_bar_mcpercent, 200);
lv_obj_set_height( ui_status_bar_mcpercent, 12);
lv_obj_set_x( ui_status_bar_mcpercent, 0 );
lv_obj_set_y( ui_status_bar_mcpercent, 14 );
lv_obj_set_align( ui_status_bar_mcpercent, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_status_bar_mcpercent, lv_color_hex(0x012401), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_mcpercent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_bar_mcpercent, lv_color_hex(0x04FE48), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_bar_mcpercent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_status_bar_mcpercent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_status_bar_mcpercent, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_status_bar_mcpercent, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_bar_mcpercent, lv_color_hex(0x00FF1C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_bar_mcpercent, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_bar_mcpercent, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_status_bar_mcpercent, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_panel_page2 = lv_obj_create(ui_screen_status);
lv_obj_set_width( ui_status_panel_page2, 220);
lv_obj_set_height( ui_status_panel_page2, 220);
lv_obj_set_x( ui_status_panel_page2, 0 );
lv_obj_set_y( ui_status_panel_page2, 39 );
lv_obj_set_align( ui_status_panel_page2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_panel_page2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status_panel_page2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_status_panel_page2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_panel_page2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_panel_page2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_panel_page2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_status_panel_page2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_panel_page2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_panel_page2, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_mcremaintime = lv_label_create(ui_status_panel_page2);
lv_obj_set_width( ui_status_label_mcremaintime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_mcremaintime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_mcremaintime, 0 );
lv_obj_set_y( ui_status_label_mcremaintime, -12 );
lv_obj_set_align( ui_status_label_mcremaintime, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_mcremaintime,"--:--");
lv_obj_set_style_text_color(ui_status_label_mcremaintime, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_mcremaintime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_mcremaintime, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_clock = lv_label_create(ui_status_panel_page2);
lv_obj_set_width( ui_status_label_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_clock, 0 );
lv_obj_set_y( ui_status_label_clock, 88 );
lv_obj_set_align( ui_status_label_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_clock,"--:--:--");
lv_obj_set_style_text_color(ui_status_label_clock, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_clock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_clock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_arc_mcpercentarc = lv_arc_create(ui_status_panel_page2);
lv_obj_set_width( ui_status_arc_mcpercentarc, 200);
lv_obj_set_height( ui_status_arc_mcpercentarc, 200);
lv_obj_set_x( ui_status_arc_mcpercentarc, 0 );
lv_obj_set_y( ui_status_arc_mcpercentarc, -5 );
lv_obj_set_align( ui_status_arc_mcpercentarc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_arc_mcpercentarc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_arc_mcpercentarc, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_status_arc_mcpercentarc, 0);
lv_obj_set_style_outline_width(ui_status_arc_mcpercentarc, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_status_arc_mcpercentarc, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_status_arc_mcpercentarc, lv_color_hex(0x00270E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_arc_mcpercentarc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_status_arc_mcpercentarc, 36, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status_arc_mcpercentarc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status_arc_mcpercentarc, lv_color_hex(0x00FF59), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status_arc_mcpercentarc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_status_arc_mcpercentarc, 36, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status_arc_mcpercentarc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_status_arc_mcpercentarc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_arc_mcpercentarc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_status_label_layernum = lv_label_create(ui_status_panel_page2);
lv_obj_set_width( ui_status_label_layernum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_layernum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_layernum, 0 );
lv_obj_set_y( ui_status_label_layernum, 30 );
lv_obj_set_align( ui_status_label_layernum, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_layernum,"-");
lv_obj_set_style_text_color(ui_status_label_layernum, lv_color_hex(0x0290FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_layernum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_layernum, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_label_layernum, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_status_label_layernum, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_status_label_layernum, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_layertotal = lv_label_create(ui_status_panel_page2);
lv_obj_set_width( ui_status_label_layertotal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_label_layertotal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_layertotal, 0 );
lv_obj_set_y( ui_status_label_layertotal, 55 );
lv_obj_set_align( ui_status_label_layertotal, LV_ALIGN_CENTER );
lv_label_set_text(ui_status_label_layertotal,"-");
lv_obj_set_style_text_color(ui_status_label_layertotal, lv_color_hex(0x0290FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_layertotal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_layertotal, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_label_layertotal, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_label_layertotal, lv_color_hex(0x003BFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_label_layertotal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_status_label_layertotal, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_status_label_layertotal, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_panel_page3 = lv_obj_create(ui_screen_status);
lv_obj_set_width( ui_status_panel_page3, 220);
lv_obj_set_height( ui_status_panel_page3, 220);
lv_obj_set_x( ui_status_panel_page3, 0 );
lv_obj_set_y( ui_status_panel_page3, 39 );
lv_obj_set_align( ui_status_panel_page3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_panel_page3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status_panel_page3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_status_panel_page3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_panel_page3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_panel_page3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_status_panel_page3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_status_panel_page3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_status_panel_page3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_panel_page3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_status_panel_page3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_image_checker = lv_img_create(ui_status_panel_page3);
lv_img_set_src(ui_status_image_checker, &ui_img_empty_png);
lv_obj_set_width( ui_status_image_checker, 55);
lv_obj_set_height( ui_status_image_checker, 160);
lv_obj_set_x( ui_status_image_checker, -55 );
lv_obj_set_y( ui_status_image_checker, -4 );
lv_obj_set_align( ui_status_image_checker, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_image_checker, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_image_checker, LV_SCROLLBAR_MODE_OFF);

ui_status_button_slot1 = lv_btn_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_button_slot1, 55);
lv_obj_set_height( ui_status_button_slot1, 28);
lv_obj_set_x( ui_status_button_slot1, -55 );
lv_obj_set_y( ui_status_button_slot1, -67 );
lv_obj_set_align( ui_status_button_slot1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_button_slot1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_button_slot1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_status_button_slot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_slot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_slot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_button_slot1, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_status_button_slot1, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_status_button_slot1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_status_button_slot1, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_slot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_slot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_button_slot2 = lv_btn_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_button_slot2, 55);
lv_obj_set_height( ui_status_button_slot2, 24);
lv_obj_set_x( ui_status_button_slot2, -55 );
lv_obj_set_y( ui_status_button_slot2, -35 );
lv_obj_set_align( ui_status_button_slot2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_button_slot2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_status_button_slot2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_slot2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_slot2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_button_slot2, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_status_button_slot2, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_status_button_slot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_status_button_slot2, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_slot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_slot2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_button_slot3 = lv_btn_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_button_slot3, 55);
lv_obj_set_height( ui_status_button_slot3, 24);
lv_obj_set_x( ui_status_button_slot3, -55 );
lv_obj_set_y( ui_status_button_slot3, -5 );
lv_obj_set_align( ui_status_button_slot3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_button_slot3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_button_slot3, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_status_button_slot3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_slot3, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_slot3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_button_slot3, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_status_button_slot3, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_status_button_slot3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_status_button_slot3, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_slot3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_slot3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_button_slot4 = lv_btn_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_button_slot4, 55);
lv_obj_set_height( ui_status_button_slot4, 24);
lv_obj_set_x( ui_status_button_slot4, -55 );
lv_obj_set_y( ui_status_button_slot4, 25 );
lv_obj_set_align( ui_status_button_slot4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_button_slot4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_button_slot4, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_status_button_slot4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_slot4, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_slot4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_button_slot4, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_status_button_slot4, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_status_button_slot4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_status_button_slot4, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_slot4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_slot4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_button_slot0 = lv_btn_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_button_slot0, 55);
lv_obj_set_height( ui_status_button_slot0, 24);
lv_obj_set_x( ui_status_button_slot0, -55 );
lv_obj_set_y( ui_status_button_slot0, 66 );
lv_obj_set_align( ui_status_button_slot0, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_button_slot0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_button_slot0, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_status_button_slot0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_button_slot0, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_button_slot0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_status_button_slot0, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_status_button_slot0, 127, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_status_button_slot0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_status_button_slot0, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_status_button_slot0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_status_button_slot0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_image_amsbox = lv_img_create(ui_status_panel_page3);
lv_img_set_src(ui_status_image_amsbox, &ui_img_ams_box_png);
lv_obj_set_width( ui_status_image_amsbox, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status_image_amsbox, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_image_amsbox, -53 );
lv_obj_set_y( ui_status_image_amsbox, 1 );
lv_obj_set_align( ui_status_image_amsbox, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status_image_amsbox, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status_image_amsbox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status_label_filament1 = lv_label_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_label_filament1, 100);
lv_obj_set_height( ui_status_label_filament1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_filament1, 103 );
lv_obj_set_y( ui_status_label_filament1, -67 );
lv_obj_set_align( ui_status_label_filament1, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_status_label_filament1,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_filament1,"-");
lv_obj_clear_flag( ui_status_label_filament1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_filament1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_filament1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_filament1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_filament1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_filament2 = lv_label_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_label_filament2, 100);
lv_obj_set_height( ui_status_label_filament2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_filament2, 103 );
lv_obj_set_y( ui_status_label_filament2, -35 );
lv_obj_set_align( ui_status_label_filament2, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_status_label_filament2,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_filament2,"-");
lv_obj_clear_flag( ui_status_label_filament2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_filament2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_filament2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_filament2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_filament2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_filament3 = lv_label_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_label_filament3, 100);
lv_obj_set_height( ui_status_label_filament3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_filament3, 103 );
lv_obj_set_y( ui_status_label_filament3, -5 );
lv_obj_set_align( ui_status_label_filament3, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_status_label_filament3,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_filament3,"-");
lv_obj_clear_flag( ui_status_label_filament3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_filament3, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_filament3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_filament3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_filament3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_filament4 = lv_label_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_label_filament4, 100);
lv_obj_set_height( ui_status_label_filament4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_filament4, 103 );
lv_obj_set_y( ui_status_label_filament4, 25 );
lv_obj_set_align( ui_status_label_filament4, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_status_label_filament4,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_filament4,"-");
lv_obj_clear_flag( ui_status_label_filament4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_filament4, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_filament4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_filament4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_filament4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_status_label_filament0 = lv_label_create(ui_status_panel_page3);
lv_obj_set_width( ui_status_label_filament0, 100);
lv_obj_set_height( ui_status_label_filament0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status_label_filament0, 103 );
lv_obj_set_y( ui_status_label_filament0, 66 );
lv_obj_set_align( ui_status_label_filament0, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_status_label_filament0,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_status_label_filament0,"-");
lv_obj_clear_flag( ui_status_label_filament0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_status_label_filament0, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_status_label_filament0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_status_label_filament0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_status_label_filament0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_status_button_networksetup, ui_event_status_button_networksetup, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_status_panel_page0, ui_event_status_panel_page0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_status, ui_event_screen_status, LV_EVENT_ALL, NULL);

}

void ui_screen_status_screen_destroy(void)
{
   if (ui_screen_status) lv_obj_del(ui_screen_status);

// NULL screen variables
ui_screen_status= NULL;
ui_status_label_printstage= NULL;
ui_status_label_wifisymbol= NULL;
ui_status_image_printer= NULL;
ui_status_image_ams= NULL;
ui_status_button_networksetup= NULL;
ui_status_label_label1= NULL;
ui_status_panel_page0= NULL;
ui_status_image_swing= NULL;
ui_status_bar_mcpercent2= NULL;
ui_status_image_ppimage= NULL;
ui_status_label_ppmessage= NULL;
ui_status_panel_page1= NULL;
ui_status_image_printbase= NULL;
ui_status_image_printhead= NULL;
ui_status_label_nozzletemp= NULL;
ui_status_label_bedtemp= NULL;
ui_status_label_chambertemp= NULL;
ui_status_bar_coolingfan= NULL;
ui_status_bar_heatbreakfan= NULL;
ui_status_spinner_spinner2= NULL;
ui_status_spinner_spinner1= NULL;
ui_status_bar_mcpercent= NULL;
ui_status_panel_page2= NULL;
ui_status_label_mcremaintime= NULL;
ui_status_label_clock= NULL;
ui_status_arc_mcpercentarc= NULL;
ui_status_label_layernum= NULL;
ui_status_label_layertotal= NULL;
ui_status_panel_page3= NULL;
ui_status_image_checker= NULL;
ui_status_button_slot1= NULL;
ui_status_button_slot2= NULL;
ui_status_button_slot3= NULL;
ui_status_button_slot4= NULL;
ui_status_button_slot0= NULL;
ui_status_image_amsbox= NULL;
ui_status_label_filament1= NULL;
ui_status_label_filament2= NULL;
ui_status_label_filament3= NULL;
ui_status_label_filament4= NULL;
ui_status_label_filament0= NULL;

}
