// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef UI_SCREEN_SETUP_H
#define UI_SCREEN_SETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_setup
extern void ui_screen_setup_screen_init(void);
extern void ui_screen_setup_screen_destroy(void);
extern void ui_event_screen_setup( lv_event_t * e);
extern lv_obj_t *ui_screen_setup;
extern lv_obj_t *ui_setup_label_info;
extern void ui_event_setup_button_close( lv_event_t * e);
extern lv_obj_t *ui_setup_button_close;
extern lv_obj_t *ui_setup_label_setup_label2;
extern lv_obj_t *ui_setup_image_image2;
extern lv_obj_t *ui_setup_label_info1;
extern lv_obj_t *ui_setup_image_image3;
extern lv_obj_t *ui_setup_label_label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

