// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: printpoop

#include "ui.h"

lv_obj_t *ui_screen_intro;
lv_obj_t *ui_intro_image_cap;
lv_obj_t *ui_intro_label_version;
lv_obj_t *ui_intro_image_icon;

// event funtions
void ui_event_screen_intro( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      spin_Animation(ui_intro_image_cap, 0);
      gif_Animation(ui_intro_image_icon, 0);
      wait5second( e );
}
}

// build funtions

void ui_screen_intro_screen_init(void)
{
ui_screen_intro = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_intro, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_screen_intro, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_img_src( ui_screen_intro, &ui_img_front_cover_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_intro_image_cap = lv_img_create(ui_screen_intro);
lv_img_set_src(ui_intro_image_cap, &ui_img_cap_png);
lv_obj_set_width( ui_intro_image_cap, 102);
lv_obj_set_height( ui_intro_image_cap, 102);
lv_obj_set_x( ui_intro_image_cap, -33 );
lv_obj_set_y( ui_intro_image_cap, 104 );
lv_obj_set_align( ui_intro_image_cap, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_intro_image_cap, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_intro_image_cap, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_intro_image_cap,300);
lv_obj_set_scrollbar_mode(ui_intro_image_cap, LV_SCROLLBAR_MODE_OFF);

ui_intro_label_version = lv_label_create(ui_screen_intro);
lv_obj_set_width( ui_intro_label_version, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_intro_label_version, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_intro_label_version, 2 );
lv_obj_set_y( ui_intro_label_version, 2 );
lv_label_set_text(ui_intro_label_version,"0.0.0");
lv_obj_set_style_text_color(ui_intro_label_version, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_intro_label_version, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_intro_label_version, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_intro_label_version, &ui_font_orangekid32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_intro_image_icon = lv_img_create(ui_screen_intro);
lv_img_set_src(ui_intro_image_icon, &ui_img_cat1_png);
lv_obj_set_width( ui_intro_image_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_intro_image_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_intro_image_icon, 74 );
lv_obj_set_y( ui_intro_image_icon, 111 );
lv_obj_set_align( ui_intro_image_icon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_intro_image_icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_intro_image_icon, LV_SCROLLBAR_MODE_OFF);

lv_obj_add_event_cb(ui_screen_intro, ui_event_screen_intro, LV_EVENT_ALL, NULL);

}

void ui_screen_intro_screen_destroy(void)
{
   if (ui_screen_intro) lv_obj_del(ui_screen_intro);

// NULL screen variables
ui_screen_intro= NULL;
ui_intro_image_cap= NULL;
ui_intro_label_version= NULL;
ui_intro_image_icon= NULL;

}
