// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef UI_SCREEN_STATUS_H
#define UI_SCREEN_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_status
extern void ui_screen_status_screen_init(void);
extern void ui_screen_status_screen_destroy(void);
extern void ui_event_screen_status( lv_event_t * e);
extern lv_obj_t *ui_screen_status;
extern lv_obj_t *ui_status_label_printstage;
extern lv_obj_t *ui_status_label_wifisymbol;
extern lv_obj_t *ui_status_image_printer;
extern lv_obj_t *ui_status_image_ams;
extern void ui_event_status_button_networksetup( lv_event_t * e);
extern lv_obj_t *ui_status_button_networksetup;
extern lv_obj_t *ui_status_label_label1;
extern void ui_event_status_panel_page0( lv_event_t * e);
extern lv_obj_t *ui_status_panel_page0;
extern lv_obj_t *ui_status_image_swing;
extern lv_obj_t *ui_status_bar_mcpercent2;
extern lv_obj_t *ui_status_image_ppimage;
extern lv_obj_t *ui_status_label_ppmessage;
extern lv_obj_t *ui_status_panel_page1;
extern lv_obj_t *ui_status_image_printbase;
extern lv_obj_t *ui_status_image_printhead;
extern lv_obj_t *ui_status_label_nozzletemp;
extern lv_obj_t *ui_status_label_bedtemp;
extern lv_obj_t *ui_status_label_chambertemp;
extern lv_obj_t *ui_status_bar_coolingfan;
extern lv_obj_t *ui_status_bar_heatbreakfan;
extern lv_obj_t *ui_status_spinner_spinner2;
extern lv_obj_t *ui_status_spinner_spinner1;
extern lv_obj_t *ui_status_bar_mcpercent;
extern lv_obj_t *ui_status_panel_page2;
extern lv_obj_t *ui_status_label_mcremaintime;
extern lv_obj_t *ui_status_label_clock;
extern lv_obj_t *ui_status_arc_mcpercentarc;
extern lv_obj_t *ui_status_panel_page3;
extern lv_obj_t *ui_status_image_checker;
extern lv_obj_t *ui_status_button_slot1;
extern lv_obj_t *ui_status_button_slot2;
extern lv_obj_t *ui_status_button_slot3;
extern lv_obj_t *ui_status_button_slot4;
extern lv_obj_t *ui_status_button_slot0;
extern lv_obj_t *ui_status_image_amsbox;
extern lv_obj_t *ui_status_label_filament1;
extern lv_obj_t *ui_status_label_filament2;
extern lv_obj_t *ui_status_label_filament3;
extern lv_obj_t *ui_status_label_filament4;
extern lv_obj_t *ui_status_label_filament0;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

