// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: printpoop

#include "ui.h"

lv_obj_t *ui_screen_setup;
lv_obj_t *ui_setup_label_info;
lv_obj_t *ui_setup_button_close;
lv_obj_t *ui_setup_label_setup_label2;
lv_obj_t *ui_setup_image_image2;
lv_obj_t *ui_setup_label_info1;
lv_obj_t *ui_setup_image_image3;
lv_obj_t *ui_setup_label_label2;

// event funtions
void ui_event_screen_setup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      openSetupPortal( e );
}
}

void ui_event_setup_button_close( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_screen_status, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_screen_status_screen_init);
      closeSetupScreen( e );
}
}

// build funtions

void ui_screen_setup_screen_init(void)
{
ui_screen_setup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_setup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_screen_setup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_setup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_info = lv_label_create(ui_screen_setup);
lv_obj_set_width( ui_setup_label_info, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_info, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_info, -52 );
lv_obj_set_y( ui_setup_label_info, -71 );
lv_obj_set_align( ui_setup_label_info, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_info,"Connect WiFi to SSID\n\"PrintpooP_Setup\"\nor \nScan QR Code ->");
lv_obj_clear_flag( ui_setup_label_info, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_setup_label_info, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_setup_label_info, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_button_close = lv_btn_create(ui_screen_setup);
lv_obj_set_width( ui_setup_button_close, 100);
lv_obj_set_height( ui_setup_button_close, 40);
lv_obj_set_x( ui_setup_button_close, -3 );
lv_obj_set_y( ui_setup_button_close, 0 );
lv_obj_set_align( ui_setup_button_close, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_button_close, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_close, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_close, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_close, lv_color_hex(0x002BFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_close, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_close, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_setup_label2 = lv_label_create(ui_setup_button_close);
lv_obj_set_width( ui_setup_label_setup_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_setup_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_setup_label2, 0 );
lv_obj_set_y( ui_setup_label_setup_label2, -1 );
lv_obj_set_align( ui_setup_label_setup_label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_setup_label2,"CLOSE");
lv_obj_set_style_text_font(ui_setup_label_setup_label2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_image_image2 = lv_img_create(ui_screen_setup);
lv_img_set_src(ui_setup_image_image2, &ui_img_ap_qr_png);
lv_obj_set_width( ui_setup_image_image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_image_image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_image_image2, 66 );
lv_obj_set_y( ui_setup_image_image2, -71 );
lv_obj_set_align( ui_setup_image_image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_setup_image_image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_setup_image_image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_setup_label_info1 = lv_label_create(ui_screen_setup);
lv_obj_set_width( ui_setup_label_info1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_info1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_info1, -56 );
lv_obj_set_y( ui_setup_label_info1, 48 );
lv_obj_set_align( ui_setup_label_info1, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_info1,"After connected\nnavigate to \n192.168.4.1\nor \nscan QR Code->");
lv_obj_clear_flag( ui_setup_label_info1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_setup_label_info1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_setup_label_info1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_image_image3 = lv_img_create(ui_screen_setup);
lv_img_set_src(ui_setup_image_image3, &ui_img_ipaddress_png);
lv_obj_set_width( ui_setup_image_image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_image_image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_image_image3, 66 );
lv_obj_set_y( ui_setup_image_image3, 51 );
lv_obj_set_align( ui_setup_image_image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_setup_image_image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_setup_image_image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_setup_label_label2 = lv_label_create(ui_screen_setup);
lv_obj_set_width( ui_setup_label_label2, lv_pct(100));
lv_obj_set_height( ui_setup_label_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_setup_label_label2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_setup_label_label2,"Network Setup");
lv_obj_set_scrollbar_mode(ui_setup_label_label2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_setup_label_label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_label_label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_setup_label_label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_label_label2, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_label_label2, lv_color_hex(0xFDE406), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_label_label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_setup_button_close, ui_event_setup_button_close, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_setup, ui_event_screen_setup, LV_EVENT_ALL, NULL);

}

void ui_screen_setup_screen_destroy(void)
{
   if (ui_screen_setup) lv_obj_del(ui_screen_setup);

// NULL screen variables
ui_screen_setup= NULL;
ui_setup_label_info= NULL;
ui_setup_button_close= NULL;
ui_setup_label_setup_label2= NULL;
ui_setup_image_image2= NULL;
ui_setup_label_info1= NULL;
ui_setup_image_image3= NULL;
ui_setup_label_label2= NULL;

}
